## Creating a range of tensors and tensors-like

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Use torch.range()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
one_to_ten.dtype

torch.int64

In [7]:
at_77 = torch.arange(start=0, end=1000, step=77)
at_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

## Creating tensors-like

In [9]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
ten_ones = torch.ones_like(input=ten_zeros)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
x_rand = torch.rand_like(input=ten_ones, dtype=torch.float)
x_rand

tensor([0.9826, 0.7438, 0.8996, 0.1262, 0.1705, 0.1821, 0.6949, 0.3272, 0.7986,
        0.4667])