In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating Tensors

In [2]:
# Scalar:

scalar1 = torch.tensor(7)
scalar1

tensor(7)

In [3]:
scalar1.item()

7

In [4]:
# numbers of dimensions
# A scalar has not dimensions

scalar1.ndim

0

In [5]:
scalar_2 = torch.tensor(5)
scalar_2

tensor(5)

### Creating a Vector

In [6]:
vector = torch.tensor([7,7,8,9])
vector

tensor([7, 7, 8, 9])

In [7]:
# A vector has 2 dimensions

vector.ndim

1

In [8]:
vector.shape

torch.Size([4])

### MATRIX

In [13]:
MATRIX = torch.tensor([[7,8,8], [9,8,10], [7,52,11]])
MATRIX

tensor([[ 7,  8,  8],
        [ 9,  8, 10],
        [ 7, 52, 11]])

In [15]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([7, 8, 8])

In [17]:
MATRIX[1]

tensor([ 9,  8, 10])

In [20]:
MATRIX.shape

torch.Size([3, 3])

### TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,6,5,8],
                        [7,8,5,7]]],
                        [[[1,2,3,4],
                        [3,6,5,8],
                        [7,8,5,7]]])

TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 5, 8],
         [7, 8, 5, 7]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 4])

In [34]:
TENSOR[0][1][2]

tensor(5)

## Random Tensor

Random tensors are importatn because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those random numbers to better represent the data.

In [35]:
### Create a random tensor (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5465, 0.3735, 0.3424, 0.6467],
        [0.1522, 0.4158, 0.7667, 0.0160],
        [0.5758, 0.3090, 0.2323, 0.1317]])

In [36]:
random_tensor.ndim

2

In [44]:
new_tensor = torch.rand(7,5)
new_tensor

tensor([[0.6756, 0.7913, 0.0331, 0.2587, 0.9855],
        [0.7232, 0.5162, 0.7560, 0.2000, 0.6858],
        [0.1253, 0.8327, 0.3682, 0.6100, 0.6225],
        [0.6618, 0.2112, 0.4421, 0.5368, 0.6252],
        [0.1799, 0.3359, 0.7325, 0.3958, 0.6053],
        [0.8742, 0.8138, 0.7234, 0.5384, 0.5463],
        [0.4241, 0.6669, 0.1275, 0.6730, 0.3399]])

## Zeros and ones

In [46]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32